#! /bin/bash

dir="./bin"

usage() {
	echo "Usage: plot_obj [OPTION]"
	echo -e "\nOption:"
	echo -e "\t-i [DIR], input 1 directory"
	echo -e "\t-j [DIR], input 2 directory"
	echo -e "\t-d [COLUMN], ploting column (Default: 2)"
	echo -e "\t-n #, Number of object in data 1(Default: 1)"
	echo -e "\t-m #, Number of object in data 2(Default: 1)"
	echo -e "Example:"
	echo -e "plot_obj -i data -n 4 -d 2"
}
num=1
num2=1
col=2
while getopts ":i:j:d:n:m:" o;do
	case $o in
		i)
			input=$OPTARG
			;;
		j)
			input2=$OPTARG
			;;
		d)
			col=$OPTARG
			;;
		n)
			num=$OPTARG
			;;
		m)
			num2=$OPTARG
			;;
		*)
			usage
			;;
	esac
done
shift $((OPTIND-1))
if [ -z "$input" ] ;then
	usage
	exit
fi
printf "set grid;plot " > .tmplot.p
for (( i=0; i<$num; i++ ));do
	find $input -name "obj_$i" | while read file;do
	printf "$cmd '$file' using 1:$col with line," >> .tmplot.p
done
done
if [ -n "$input2" ];then
	for (( i=0; i<$num2; i++ ));do
		find $input2 -name "obj_$i" | while read file;do
		printf "$cmd '$input2/obj_$i' using 1:$col with line," >> .tmplot.p
	done
	done
fi
printf ";pause -1" >> .tmplot.p
gnuplot .tmplot.p

