#! /bin/bash

dir="./bin"
if [ -z "$1" ];then
	echo "Missing configuration file"
	exit
fi
output=`grep 'DIR_NAME' $1 | cut -d ' ' -f 2`
mkdir $output 2> /dev/null
rm -rf $output/* 2> /dev/null
(time -p $dir/launcher $1) |& tee -a $output/log
