#! /bin/bash

usage() {
	echo "Usage: schedule [EXP_LIST]"
}
if [ -z "$1" ];then
	usage
	exit
fi
num=1
total=`wc -l $1 | cut -d ' ' -f 1`
cat $1 | while read line;do
printf "Processing [$line]\t($num/$total):\n"
./simulator $line
num=$((num+1))
done
