#! /bin/bash

dir="/home/jerry/Projects/LBM_CYMB/bin"
if [ -z "$1" ];then
	echo "Missing experiment dir"
	exit
fi
conf=`ls $1 | grep '.conf'`
output=`grep 'OUTPUT_DIR' $1/$conf | cut -d ' ' -f 2`
if [ -d "$1/$output" ];then
	mkdir $1/$output 2> /dev/null
	rm -rf $1/$output/* 2> /dev/null
fi
echo "" > $1/log
echo "" > $1/debug
(cd $1 && (time -p $dir/launcher $conf) |& tee -a ./log)
#cd $1 && ($dir/launcher $conf)
