#! /bin/bash

pd_dir="./pd_auto"

usage() {
	echo "Usage: speed_test [EXP_DIR]"
}

if [ -z "$1" ] ;then
	usage
	exit
fi
x=`head -n 1 $1/a.nd | cut -d ' ' -f 1`
y=`head -n 1 $1/a.nd | cut -d ' ' -f 2`

echo '#Syntax: pdFileName[platform device localSize1 localSize2] realTime(secs)'
echo '#'
printf "Working on..."
printf '' > .speed_test_rst
cp $1/a.pd $1/b.pd
pdFileNum=`ls $pd_dir | wc -l`
num=0
ls $pd_dir | grep .pd | while read file;do
	num=$((num+1))
	printf "\rWorking on...($num/$pdFileNum)"
	cp $pd_dir/$file $1/a.pd
	info=`cat $pd_dir/$file | sed 's/ /\//g'`
	Time=`{ time -p ./simulator $1; }  2>&1 > /dev/null`
	if [ "$?" -eq "0" ];then
		realTime=`echo $Time | cut -d ' ' -f 2`
		printf "%-50s\t" "$file[$info]" >> .speed_test_rst
		echo $realTime >> .speed_test_rst
	fi
done
printf "\rWorking on...completed!\n"
sort .speed_test_rst -nk 2,2
mv $1/b.pd $1/a.pd
rm .speed_test_rst

