#! /bin/bash
name="2c_offset"
dir=`pwd`
mid="240"
printf "" > 2c.sch
for i in `seq 40 10 160`;do
	rm -r $dir/$name-$i 2> /dev/null
	cp $dir/tmp -r $dir/$name-$i
	sed -i "s/C1X/$((mid-i))/" $dir/$name-$i/a.bc
	sed -i "s/C2X/$((mid+i))/" $dir/$name-$i/a.bc
	printf "create exp_sets/$name-$i\n"
	printf "$dir/$name-$i\n" >> 2c.sch
done
